export const ERROR = {
  NOT_FOUND: 'NOT_FOUND',
  INVALID_DATA: 'INVALID_DATA',
  DUPLICATE_DATA: 'DUPLICATE_DATA',
  UNAUTHENTICATED: 'UNAUTHENTICATED',
  PERMISSION_DENIED: 'PERMISSION_DENIED',
  INVALID_FOREIGN_KEY: 'INVALID_FOREIGN_KEY',
  INVALID_CREDENTIALS: 'INVALID_CREDENTIALS',
};

export const ATTACHMENT_TYPE = {
  IMAGE: 'IMAGE',
  AUDIO: 'AUDIO',
  VIDEO: 'VIDEO',
  DOCUMENT: 'DOCUMENT',
};

export const PUBSUB = {
  MESSAGE: {
    USERS: 'USERS',
    CHATS: 'CHATS',
    MESSAGES: 'MESSAGES',
  },
  MESSAGE_TYPES: {
    USER_UPDATED: 'USER_UPDATED',
    USER_DELETED: 'USER_DELETED',
    CHAT_CREATED: 'CHAT_CREATED',
    CHAT_UPDATED: 'CHAT_UPDATED',
    CHAT_DELETED: 'CHAT_DELETED',
    MESSAGE_CREATED: 'MESSAGE_CREATED',
    MESSAGE_UPDATED: 'MESSAGE_UPDATED',
    MESSAGE_DELETED: 'MESSAGE_DELETED',
  },
};
